version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
        interval: "weekly"
        day: "monday"
        time: "05:57"
        timezone: "Europe/Stockholm"
    groups:
      dev-tooling:
        patterns: ["eslint*", "typescript-eslint*", "globals*"]

    ignore:
      - dependency-name: eslint
        versions: ["10.x"]

  - package-ecosystem: docker
    directory: /
    schedule:
        interval: "weekly"
        day: "monday"
        time: "05:57"
        timezone: "Europe/Stockholm"

  - package-ecosystem: github-actions
    directory: /
    schedule:
        interval: "weekly"
        day: "monday"
        time: "05:57"
        timezone: "Europe/Stockholm"
    groups:
      actions:
        patterns: ["*"]
